### PR TITLE
create P for C & C1

### PR DESCRIPTION
**Pull request by VirtuXYz**

### CODE REVIEW

**Review by Ti-gersh-ark — COMMENTED** [review]
You might need to use variable Player1 and 2

**Review by JohannaChu — COMMENTED** [review]
good code!

**Review by Jin114114 — COMMENTED** [review]
The best code I’ve ever seen! 👍

**Comment by Jin114114** [comment]
Adding judgement of repeated occupation may make it better

**Review by Ti-gersh-ark — APPROVED** [review]
੭ ᐕ)੭

**Pull request merged**
